CREATE TABLE user (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL
);